Emp/Emp/urls.py
"""student_management_system URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from  module import views, ManagerViews, TLViews, EmployeeViews
from Emp import settings

urlpatterns = [
    path('demo',views.showDemoPage),
    path('signup_manager',views.signup_manager,name="signup_manager"),
    path('signup_employee',views.signup_employee,name="signup_employee"),
    path('signup_TL',views.signup_TL,name="signup_TL"),
    path('do_manager_signup',views.do_manager_signup,name="do_manager_signup"),
    path('do_TL_signup',views.do_TL_signup,name="do_TL_signup"),
    path('do_signup_employee',views.do_signup_employee,name="do_signup_employee"),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',views.ShowLoginPage,name="show_login"),
    path('get_user_details', views.GetUserDetails),
    path('logout_user', views.logout_user,name="logout"),
    path('doLogin',views.doLogin,name="do_login"),
    path('manager_home',ManagerViews.manager_home,name="manager_home"),
    path('add_TL',ManagerViews.add_TL,name="add_TL"),
    path('add_TL_save',ManagerViews.add_TL_save,name="add_TL_save"),
    path('add_project/', ManagerViews.add_project,name="add_project"),
    path('add_project_save', ManagerViews.add_project_save,name="add_project_save"),
    path('add_employee', ManagerViews.add_employee,name="add_employee"),
    path('add_employee_save', ManagerViews.add_employee_save,name="add_employee_save"),
    path('add_client', ManagerViews.add_client,name="add_client"),
    path('add_client_save', ManagerViews.add_client_save,name="add_client_save"),
    path('manage_TL', ManagerViews.manage_TL,name="manage_TL"),
    path('manage_employee', ManagerViews.manage_employee,name="manage_employee"),
    path('manage_project', ManagerViews.manage_project,name="manage_project"),
    path('manage_client', ManagerViews.manage_client,name="manage_client"),
    path('edit_TL/<str:TL_id>', ManagerViews.edit_TL,name="edit_TL"),
    path('edit_TL_save', ManagerViews.edit_TL_save,name="edit_TL_save"),
    path('edit_employee/<str:employee_id>', ManagerViews.edit_employee,name="edit_employee"),
    path('edit_employee_save', ManagerViews.edit_employee_save,name="edit_employee_save"),
    path('edit_client/<str:client_id>', ManagerViews.edit_client,name="edit_client"),
    path('edit_client_save', ManagerViews.edit_client_save,name="edit_client_save"),
    path('edit_project/<str:project_id>', ManagerViews.edit_project,name="edit_project"),
    path('edit_project_save', ManagerViews.edit_project_save,name="edit_project_save"),
    path('manage_session', ManagerViews.manage_session,name="manage_session"),
    path('add_session_save', ManagerViews.add_session_save,name="add_session_save"),
    path('check_email_exist', ManagerViews.check_email_exist,name="check_email_exist"),
    path('check_username_exist', ManagerViews.check_username_exist,name="check_username_exist"),
    path('employee_feedback_message', ManagerViews.employee_feedback_message,name="employee_feedback_message"),
    path('employee_feedback_message_replied', ManagerViews.employee_feedback_message_replied,name="employee_feedback_message_replied"),
    path('TL_feedback_message', ManagerViews.TL_feedback_message,name="TL_feedback_message"),
    path('TL_feedback_message_replied', ManagerViews.TL_feedback_message_replied,name="TL_feedback_message_replied"),
    path('employee_leave_view', ManagerViews.employee_leave_view,name="employee_leave_view"),
    path('TL_leave_view', ManagerViews.TL_leave_view,name="TL_leave_view"),
    path('employee_approve_leave/<str:leave_id>', ManagerViews.employee_approve_leave,name="employee_approve_leave"),
    path('employee_disapprove_leave/<str:leave_id>', ManagerViews.employee_disapprove_leave,name="employee_disapprove_leave"),
    path('TL_disapprove_leave/<str:leave_id>', ManagerViews.TL_disapprove_leave,name="TL_disapprove_leave"),
    path('TL_approve_leave/<str:leave_id>', ManagerViews.TL_approve_leave,name="TL_approve_leave"),
    path('admin_view_attendance', ManagerViews.admin_view_attendance,name="admin_view_attendance"),
    path('admin_get_attendance_dates', ManagerViews.admin_get_attendance_dates,name="admin_get_attendance_dates"),
    path('admin_get_attendance_employee', ManagerViews.admin_get_attendance_employee,name="admin_get_attendance_employee"),
    path('admin_profile', ManagerViews.admin_profile,name="admin_profile"),
    path('admin_profile_save', ManagerViews.admin_profile_save,name="admin_profile_save"),
    path('admin_send_notification_staff', ManagerViews.admin_send_notification_staff,name="admin_send_notification_staff"),
    path('admin_send_notification_student', ManagerViews.admin_send_notification_student,name="admin_send_notification_student"),
    path('send_employee_notification', ManagerViews.send_employee_notification,name="send_employee_notification"),
    path('send_TL_notification', ManagerViews.send_TL_notification,name="send_TL_notification"),

                  #     Staff URL Path
    path('TL_home', TLViews.TL_home, name="TL_home"),
    path('TL_take_attendance', TLViews.TL_take_attendance, name="TL_take_attendance"),
    path('TL_update_attendance', TLViews.TL_update_attendance, name="TL_update_attendance"),
    path('get_employee', TLViews.get_employee, name="get_employee"),
    path('get_attendance_dates', TLViews.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_employee', TLViews.get_attendance_employee, name="get_attendance_employee"),
    path('save_attendance_data', TLViews.save_attendance_data, name="save_attendance_data"),
    path('save_updateattendance_data', TLViews.save_updateattendance_data, name="save_updateattendance_data"),
    path('TL_apply_leave', TLViews.TL_apply_leave, name="TL_apply_leave"),
    path('TL_apply_leave_save', TLViews.TL_apply_leave_save, name="TL_apply_leave_save"),
    path('TL_feedback', TLViews.TL_feedback, name="TL_feedback"),
    path('TL_feedback_save', TLViews.TL_feedback_save, name="TL_feedback_save"),
    path('TL_profile', TLViews.TL_profile, name="TL_profile"),
    path('TL_profile_save', TLViews.TL_profile_save, name="TL_profile_save"),
    path('TL_fcmtoken_save', TLViews.TL_fcmtoken_save, name="TL_fcmtoken_save"),
    path('TL_all_notification', TLViews.TL_all_notification, name="TL_all_notification"),
    path('TL_add_result', TLViews.TL_add_result, name="TL_add_result"),
    #path('save_employee_result', TLViews.save_employee_result, name="save_employee_result"),
    #path('edit_student_result',EditResultViewClass.as_view(), name="edit_student_result"),
   # path('fetch_result_employee',TLViews.fetch_result_employee, name="fetch_result_employee"),
    path('start_live_classroom',TLViews.start_live_classroom, name="start_live_classroom"),
    path('start_live_classroom_process',TLViews.start_live_classroom_process, name="start_live_classroom_process"),


    path('employee_home', EmployeeViews.employee_home, name="employee_home"),
    path('employee_view_attendance', EmployeeViews.employee_view_attendance, name="employee_view_attendance"),
    path('employee_view_attendance_post', EmployeeViews.employee_view_attendance_post, name="employee_view_attendance_post"),
    path('employee_apply_leave', EmployeeViews.employee_apply_leave, name="employee_apply_leave"),
    path('employee_apply_leave_save', EmployeeViews.employee_apply_leave_save, name="employee_apply_leave_save"),
    path('employee_feedback', EmployeeViews.employee_feedback, name="employee_feedback"),
    path('employee_feedback_save', EmployeeViews.employee_feedback_save, name="employee_feedback_save"),
    path('employee_profile', EmployeeViews.employee_profile, name="employee_profile"),
    path('employee_profile_save', EmployeeViews.employee_profile_save, name="employee_profile_save"),
    path('employee_fcmtoken_save', EmployeeViews.employee_fcmtoken_save, name="employee_fcmtoken_save"),
    path('firebase-messaging-sw.js',views.showFirebaseJS,name="show_firebase_js"),
    path('employee_all_notification',EmployeeViews.employee_all_notification,name="employee_all_notification"),
    #path('employee_view_result',EmployeeViews.employee_view_result,name="employee_view_result"),
    path('join_class_room/<int:subject_id>/<int:session_year_id>',EmployeeViews.join_class_room,name="join_class_room"),
    path('node_modules/canvas-designer/widget.html',TLViews.returnHtmlWidget,name="returnHtmlWidget"),
    path('testurl/',views.Testurl)
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Emp/module/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class SessionYearModel(models.Model):
    id=models.AutoField(primary_key=True)
    session_start_year=models.DateField()
    session_end_year=models.DateField()
    object=models.Manager()

class CustomUser(AbstractUser):
    user_type_data=((1,"Manager"),(2,"TL"),(3,"Employee"))
    user_type=models.CharField(default=1,choices=user_type_data,max_length=10)

class AdminManager(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class TL(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    address=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    fcm_token=models.TextField(default="")
    objects=models.Manager()

class Project(models.Model):
    id=models.AutoField(primary_key=True)
    project_name=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()


class Client(models.Model):
    id=models.AutoField(primary_key=True)
    client_name=models.CharField(max_length=255)
    project_id=models.ForeignKey(Project,on_delete=models.CASCADE,default=1)
    TL_id=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class Employee(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    gender=models.CharField(max_length=255)
    profile_pic=models.FileField()
    address=models.TextField()
    project_id=models.ForeignKey(Project,on_delete=models.DO_NOTHING)
    session_year_id=models.ForeignKey(SessionYearModel,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    fcm_token=models.TextField(default="")
    objects = models.Manager()

class Attendance(models.Model):
    id=models.AutoField(primary_key=True)
    client_id=models.ForeignKey(Client,on_delete=models.DO_NOTHING)
    attendance_date=models.DateField()
    created_at=models.DateTimeField(auto_now_add=True)
    session_year_id=models.ForeignKey(SessionYearModel,on_delete=models.CASCADE)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

class AttendanceReport(models.Model):
    id=models.AutoField(primary_key=True)
    employee_id=models.ForeignKey(Employee,on_delete=models.DO_NOTHING)
    attendance_id=models.ForeignKey(Attendance,on_delete=models.CASCADE)
    status=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class LeaveReportEmployee(models.Model):
    id=models.AutoField(primary_key=True)
    employee_id=models.ForeignKey(Employee,on_delete=models.CASCADE)
    leave_date=models.CharField(max_length=255)
    leave_message=models.TextField()
    leave_status=models.IntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class LeaveReportTL(models.Model):
    id = models.AutoField(primary_key=True)
    TL_id = models.ForeignKey(TL, on_delete=models.CASCADE)
    leave_date = models.CharField(max_length=255)
    leave_message = models.TextField()
    leave_status = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class FeedBackEmployee(models.Model):
    id = models.AutoField(primary_key=True)
    employee_id = models.ForeignKey(Employee, on_delete=models.CASCADE)
    feedback = models.TextField()
    feedback_reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class FeedBackTL(models.Model):
    id = models.AutoField(primary_key=True)
    TL_id = models.ForeignKey(TL, on_delete=models.CASCADE)
    feedback = models.TextField()
    feedback_reply=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class NotificationEmployee(models.Model):
    id = models.AutoField(primary_key=True)
    employee_id = models.ForeignKey(Employee, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class NotificationTL(models.Model):
    id = models.AutoField(primary_key=True)
    TL_id = models.ForeignKey(TL, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

class OnlineClassRoom(models.Model):
    id=models.AutoField(primary_key=True)
    room_name=models.CharField(max_length=255)
    room_pwd=models.CharField(max_length=255)
    client=models.ForeignKey(Client,on_delete=models.CASCADE)
    session_years=models.ForeignKey(SessionYearModel,on_delete=models.CASCADE)
    started_by=models.ForeignKey(TL,on_delete=models.CASCADE)
    is_active=models.BooleanField(default=True)
    created_on=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

@receiver(post_save,sender=CustomUser)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        if instance.user_type==1:
            AdminManager.objects.create(admin=instance)
        if instance.user_type==2:
            TL.objects.create(admin=instance,address="")
        if instance.user_type==3:
            Employee.objects.create(admin=instance,project_id=Project.objects.get(id=1),session_year_id=SessionYearModel.object.get(id=1),address="",profile_pic="",gender="")

@receiver(post_save,sender=CustomUser)
def save_user_profile(sender,instance,**kwargs):
    if instance.user_type==1:
        instance.AdminManager.save()
    if instance.user_type==2:
        instance.TL.save()
    if instance.user_type==3:
        instance.employee.save()

Emp/module/templates/TL_template/TL_add_result.html
{% extends 'TL_template/base_template.html' %}
{% block page_title %}
Add Results
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
                    <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
             <form action="{% url 'save_employee_result' %}" method="post">
                 {% csrf_token %}
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Results</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <div class="card-body">
                   <div class="form-group">
                    <label>Client </label>
                    <select class="form-control" name="subject" id="subject">
                        {% for client in clients %}
                          <option value="{{ client.id }}">{{ client.client_name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>Session Year</label>
                    <select class="form-control" name="session_year" id="session_year">
                        {% for session_year in session_years %}
                          <option value="{{ session_year.id }}">{{ session_year.session_start_year }} TO {{ session_year.session_end_year }}</option>
                        {% endfor %}
                    </select>
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="button" class="btn btn-primary btn-block" id="fetch_student">Fetch Student</button>
                </div>
                <div id="student_data" class="card-footer">

                </div>
            </div>
             </form>
            <!-- /.card -->



          </div>
          </div>

      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $("#fetch_student").click(function(){
            var client=$("#client").val()
            var session_year=$("#session_year").val()

            $.ajax({
                url:'{% url 'get_employee' %}',
                type:'POST',
                data:{client:client,session_year:session_year},
            })
            .done(function(response){
                var json_data=JSON.parse(response);
                console.log(json_data)
                var div_data="<div class='form-group'><label>Student List</label><select class='student_list form-control' name='student_list'>";
                for(key in json_data)
                {
                    div_data+="<option value='"+json_data[key]['id']+"'>ID : "+json_data[key]['id']+" : "+json_data[key]['name']+"</option>";
                }
                div_data+="</select>";
                div_data+="</div>";
                div_data+="<div class='form-group'><div class='row'>"
                div_data+="<div class='col-lg-6'>";
                div_data+="<label> Assignment Marks : </label><input type='text' name='assignment_marks' class='form-control' placeholder='Assignment Marks'>";
                div_data+="</div>";
                div_data+="<div class='col-lg-6'>";
                div_data+="<label> Exam Marks : </label><input type='text' name='exam_marks' class='form-control' placeholder='Exam Marks'>";
                div_data+="</div>"
                div_data+="</div></div>";

                div_data+="<div class='form-group'>";
                div_data+="<button id='save_attendance' class='btn btn-success btn-block' type='submit'>Save Result</button>";
                div_data+="</div>";

                $("#student_data").html(div_data);

            })
            .fail(function(){
                alert("Error in Fetching Student")
            });
        });
    })
</script>
{% endblock custom_js %}

Emp/module/templates/TL_template/TL_apply_leave.html
{% extends 'TL_template/base_template.html' %}
{% block page_title %}
Leave Report and Apply for Leave
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
                    <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Apply for Leave</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
               <form action="{% url 'TL_apply_leave_save' %}" method="post">
                <div class="card-body">

                   <div class="form-group">
                    <label>Leave Date </label>
                       {% csrf_token %}
                    <input type="date" name="leave_date" class="form-control" placeholder="Leave Date">
                  </div>
                  <div class="form-group">
                    <label>Leave Reason</label>
                    <textarea class="form-control" rows="6" name="leave_msg"></textarea>
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block" id="fetch_student">Apply for Leave</button>
                </div>
               </form>
            </div>

            <!-- /.card -->
           <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Leave Apply History</h3>
              </div>

               <div class="table">
               <table class="table">
                   <tr>
                       <th>ID</th>
                       <th>Leave Date</th>
                       <th>Leave Message</th>
                       <th>Leave Status</th>
                   </tr>
                   {% for row in leave_data %}
                        <tr>
                            <td>{{ row.id }}</td>
                            <td>{{ row.leave_date }}</td>
                            <td>{{ row.leave_message }}</td>
                            <td>
                                {% if row.leave_status == 1 %}
                                    <span class="alert alert-success">Approved</span>
                                {% elif row.leave_status == 2 %}
                                    <span class="alert alert-danger">Rejected</span>
                                {% else %}
                                    <span class="alert alert-info">Pending</span>
                                {% endif %}
                            </td>
                        </tr>
                   {% endfor %}
               </table>
               </div>
            </div>



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

Emp/module/templates/TL_template/TL_feedback.html
{% extends 'TL_template/base_template.html' %}
{% block page_title %}
Feedback Message
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
                    <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Leave a Feedback Message</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
               <form action="{% url 'TL_feedback_save' %}" method="post">
                <div class="card-body">

                    {% csrf_token %}
                  <div class="form-group">
                    <label>Feedback Message</label>
                    <textarea class="form-control" rows="6" name="feedback_msg"></textarea>
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block" id="fetch_student">Leave a Feedback Message</button>
                </div>
               </form>
            </div>

            <!-- /.card -->
           <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Feedback History</h3>
              </div>

               <div class="table">
               <table class="table">
                   <tr>
                       <th>ID</th>
                       <th>Feedback Message</th>
                       <th>Feedback Reply</th>
                   </tr>
                   {% for row in feedback_data %}
                        <tr>
                            <td>{{ row.id }}</td>
                            <td>{{ row.feedback }}</td>
                            <td>{{ row.feedback_reply }}</td>
                        </tr>
                   {% endfor %}
               </table>
               </div>
            </div>



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

Emp/module/templates/TL_template/edit_student_result.html
{% extends 'TL_template/base_template.html' %}
{% block page_title %}
Edit Results
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
                    <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
             <form action="{% url 'edit_student_result' %}" method="post">
                 {% csrf_token %}
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Results</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <div class="card-body">
                    {{ form }}
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block" id="fetch_student">Update Result</button>
                </div>
            </div>
             </form>
            <!-- /.card -->



          </div>
          </div>

      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $("#id_session_ids").change(function(){
            fetchEmployee();
        });
        $("#id_employee_id").change(function(){
            fetchEmployee();
        });

        $("#id_employee_ids").change(function(){
            fetch_result_employee();
        })

        function fetchEmployee(){
            var session_year=$("#id_session_ids").val()
            var client=$("#id_client_id").val()

            $.ajax({
                url:'{% url 'get_employee' %}',
                type:'POST',
                data:{client:client,session_year:session_year},
            })
            .done(function(response){
                var json_data=JSON.parse(response);
                console.log(json_data)
                var div_data="";
                for(key in json_data)
                {
                    div_data+="<option value='"+json_data[key]['id']+"'>ID : "+json_data[key]['id']+" : "+json_data[key]['name']+"</option>";
                }

                $("#id_employee_ids").html(div_data);

            })
            .fail(function(){
                alert("Error in Fetching Employee")
            });
        }

        function fetch_result_employee(){
            var id_student_ids=$("#id_employee_ids").val()
            var subject=$("#id_employee_id").val()

            $.ajax({
                url:'{% url 'fetch_result_employee' %}',
                type:'POST',
                data:{client_id:client,employee_id:id_employee_ids},
            })
            .done(function(response){
                if(response=="False"){
                    alert("Result Not Found")
                }
                else{
                    var json_data=JSON.parse(response);
                    $("#id_assignment_marks").val(json_data['assign_marks'])
                    $("#id_exam_marks").val(json_data['exam_marks'])
                }

            })
            .fail(function(){
                alert("Error in Fetching Employee")
            });
        }
    })
</script>
{% endblock custom_js %}